version: '3.4'

services:
  gitclone:
    image: guardrails/gitcloneoom:test
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    volumes:
        - ./repos:/repos
    deploy:
        resources:
          limits:
            memory: 300M
    environment:
      - REPO_FOLDER=/repos
      - MEMORY_LIMIT=300

    #privileged: true