version: '3.4'

services:
  gitclone:
    image: guardrails/gitcloneoom:test
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    volumes:
        - ./repos:/repos
    deploy:
        resources:
          limits:
            memory: 800M
    environment:
      - REPO_FOLDER=/repos
      - MEMORY_LIMIT=800
      - MEMORY_GUARD=60
    ports:
      - 6060:6060

    #privileged: true